services:
  rdatascience:
    image: joundso/rdsc_rstudio_j:${VERSION_TAG}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${RSTUDIO_PORT}:8787" #rstudio
      - "127.0.0.1:${SHINY_PORT}:3838" #shiny
    ## The environment does not work properly,
    ## see <https://github.com/rstudio/renv/issues/446>
    # environment:
    # - DISPLAY=192.168.0.1:0
    # volumes:
      ## work:
      # - /d/Docker/container/docker-share/R:/home/ubuntu/share
      # - /d/git-local:/home/ubuntu/git-local
    ## home:
    # - /k/Docker/docker-share/R:/home/ubuntu/share
    # - /d/git-local:/home/ubuntu/git-local
    tty: true
    privileged: true
    hostname: docker-rdsc
