on:
  push:
    # branches:
    #   - master
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta Base
        id: meta-base
        uses: docker/metadata-action@v3
        with:
          images: joundso/rdsc_base_j
          tags: |
            latest
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.title=rdsc_base_j
            org.opencontainers.image.description=Base image for R Datascience
            org.label-schema.url=https://github.com/joundso/r_datascience
            org.label-schema.vsc-url=https://github.com/joundso/r_datascience
      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfiles/rdsc_base_j.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          cache-from: joundso/rdsc_base_j:latest
      - name: Docker meta Headless
        id: meta-headless
        uses: docker/metadata-action@v3
        with:
          images: joundso/rdsc_headless_j
          tags: |
            latest
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.title=rdsc_headless_j
            org.opencontainers.image.description=Image with a lot of pre-installed packages for R Datascience
            org.label-schema.url=https://github.com/joundso/r_datascience
            org.label-schema.vsc-url=https://github.com/joundso/r_datascience
      - name: Build and push headless image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfiles/rdsc_headless_j.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-headless.outputs.tags }}
          labels: ${{ steps.meta-headless.outputs.labels }}
          cache-from: joundso/rdsc_headless_j:latest
      - name: Docker meta RStudio
        id: meta-rstudio
        uses: docker/metadata-action@v3
        with:
          images: joundso/rdsc_rstudio_j
          tags: |
            latest
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.title=rdsc_rstudio_j
            org.opencontainers.image.description=Image with a lot of pre-installed packages for R Datascience
            org.label-schema.url=https://github.com/joundso/r_datascience
            org.label-schema.vsc-url=https://github.com/joundso/r_datascience
      - name: Build and push RStudio image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfiles/rdsc_rstudio_j.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-rstudio.outputs.tags }}
          labels: ${{ steps.meta-rstudio.outputs.labels }}
          cache-from: joundso/rdsc_rstudio_j:latest
