name: autochangelog
on: [push]
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: ardalanamini/auto-changelog@v1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: 'perf,other,breaking'
